### ISSUE TITLE
Sometimes reconnect to validator will result in answers not being sent

### ISSUE THREAD

**Issue by TrilliumSEN** [ReserveBlockIO/ReserveBlock-Core#8] opened 2022-06-05 19:13 UTC
Sometimes on validator pool reconnect answers will stop at the time of the reconnect, but will continue to receive answer response, just won't send a question beyond that initial loss point.

**Comment by mathis1337** [comment] 2022-06-06 07:54
Advanced logging was added to determine the root cause of this. Will revisit once new information is gathered.

**Comment by mathis1337** [comment] 2022-06-10 17:30
Logging not reporting any issues. will monitor. Closing for now.

**Closed by mathis1337** 2022-06-10 17:30 UTC
Labels: bug
